### ISSUE TITLE
RuntimeError: Background initialization must be done in a scene's on_enter, not __init__

### ISSUE THREAD

**Issue by deshipu** [rdeaton/spyral#2]
When running the skel.py from the examples directory, I get the following error:

```
Traceback (most recent call last):
  File "skel.py", line 50, in <module>
    spyral.director.push(Game()) # push means that this Game() instance is
  File "skel.py", line 27, in __init__
    self.camera.set_background(bg)
  File "/.../spyral/camera.py", line 116, in set_background
    raise RuntimeError("Background initialization must be done in a scene's on_enter, not __init__")
RuntimeError: Background initialization must be done in a scene's on_enter, not __init__
```

**Comment by deshipu** [comment]
Moving the background-setting code to `on_enter` results in:

```

Traceback (most recent call last):
  File "skel.py", line 52, in <module>
    spyral.director.push(Game()) # push means that this Game() instance is
  File "/.../spyral/scene.py", line 130, in push
    scene.on_enter()
  File "skel.py", line 29, in on_enter
    self.camera.set_background(bg)
  File "/.../spyral/camera.py", line 124, in set_background
    raise ValueError("You cannot set the background on the root camera directly.")
ValueError: You cannot set the background on the root camera directly.
```
